replicaCount: 1

image:
  repository: ghrc.io/aagumin/spark-connect-kubernetes
  tag: 1.0.0
  pullPolicy: Always
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

spark:
  eventLog:
    enabled: true
    dir: ""

  awsEndpoint: ""

  driver:
    cores: 2
    memoryMiB: 2048
    memoryOverheadMiB: 384
    ephemeralLocalVolume: {}
    affinity: {}
    tolerations: []

  executor:
    cores: 8
    requestCoresMilliCPU: 4000
    memoryMiB: 20480
    memoryOverheadMiB: 5120
    ephemeralLocalVolume: {}
    minExecutors: 1
    maxExecutors: 10
    affinity: {}
    tolerations: []
    labels: {}

  scratchDir: /tmp
  kubernetesEndpoint: "https://kubernetes.default.svc.cluster.local:443"
  packages: []
  sparkConfig:
    spark.hadoop.parquet.block.size: "33554432"
    spark.driver.maxResultSize: 4g
  hiveMetastoreConfigMap: spark-connect-hive

serviceAccount:
  create: true
  annotations: {}
  name: "spark-connect"
  automountServiceAccountToken: true

service:
  create: true
  annotations: {}
  name: "spark-connect"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 185
  runAsGroup: 185

command: []
extraArgs: []
extraEnv: []

mtls:
  enabled: false
  pre.start.script: ""
  post.stop.script: ""

containerPorts:
  sparkUi: 4040
  sparkConnect: 15002
